language: node_js
node_js: "0.12"
script: npm run travisci
after_script:
  - codeclimate-test-reporter < coverage/combined/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "eRvEdui3o5Ztp8yILogtDM10X2TCIDwNFlRebpWFyaKsBkjWaVDtTl3ZFq5AaRjBMPqm0/5Ov1scpulbdjJuUKGq75kZTCQh3HlXFSqiv0qrfM+y8seUxDuB/Qd0VSlhtgIplmVdzrEW/Cvwf5G8+D6C6r0DLNvMlyXu9WO9j2t7yI/gN2UbBeY+FBrrOK2eTMUy/IbMHxw/iDqbItoykfnf3+7PHsOukNQ651BP7TOXJ88X58pNIPyUWUy6Uru1U2uqPoPrrGswOZyyqsqNbvs+sJRi1ENhgC9PrAs+VpNKVhYfh1i2Xm0MW5Ky+maOnK8hItVrhmT4m9kjLCtjtwh2XBE2p3JpZTQ0/r2AqMMnk9OZY6cnIXqBK8FAmajuoU1wS2CmeSkGpeXqt3rxopRQ3COYC/MlhVxxZs/mEM7CNE6UwNh+FCkuP6FECbhuBh10ZUH9cq0g1xb6zcW9XoQEAHrzwNTAjiPg+6wx6sXJpT+n3gx4GcyjdKpJYMycx/rc1HaVEtUhMIPGeu+1oqtrUy5dJu3MxojiceMS70vcd6bwoCkahM0tnu3TcXBg2/qb9aD/trM5hQcS6QaG8AgDy5PsArJWqezzi22BIcICJVYjVjB9a1Z4SfOg0KUZrxXhl2MnZLjUVlGOh/SSkX3T6QX2moTjv9YIB89T3DU="
